config/routes.rb
Rails.application.routes.draw do
  devise_for :mentors, controllers: { registrations: "mentors" }

  devise_scope :mentor do
    root 'mentors#root'
    resources :mentors, param: :uuid do
      collection do
        get '/results', to: 'mentors#results', as: 'results'
      end
    end
  end

  get '/privacy-policy', to: 'static#privacy_policy', as: 'privacy_policy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mentor.rb
class Mentor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates_presence_of :booking_url
  validates_presence_of :username
  has_many :mentor_tags
  has_many :tags, through: :mentor_tags
  scope :confirmed, -> { where.not(confirmation_sent_at: nil) }
  before_create :set_uuid

  private

  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/models/mentor_tag.rb
class MentorTag < ApplicationRecord
  belongs_to :mentor
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :mentor_tags
  has_many :mentors, through: :mentor_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username job_role booking_url])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username tag_ids job_role booking_url])
  end
end

app/controllers/mentors_controller.rb
class MentorsController < Devise::RegistrationsController
  protect_from_forgery prepend: true
  before_action :authenticate_mentor!, except: %i[results root]

  def index
    # @mentors = Mentor.confirmed.all
    @mentors = Mentor.all
  end

  def results
    tags = params[:tags][:ids]
    @mentors = Mentor.joins(:tags).where(tags: { id: tags }).distinct
    redirect_to_index({notice: 'There were no mentors matching your options'}) if @mentors.empty? || tags.empty?
  end

  def show
    @mentor = find_by_uuid
  end

  def edit
    conditional_action do
      @mentor = find_by_uuid
    end
  end

  def update
    conditional_action do
      mentor = find_by_uuid
      remove_blank_passwords
      mentor.update!(mentor_params)
      redirect_to mentor_path(mentor.username)
    end
  end

  def delete
    conditional_action do
      mentor = find_by_uuid
      mentor.delete
    end
  end

  def root; end

  private
  def find_by_uuid
    Mentor.find_by_uuid(params[:uuid])
  end

  def mentor_params
    params.require(:mentor).permit(:username, :password, :password_confirmation, :booking_url, :email, :job_role, tag_ids: [])
  end

  def remove_blank_passwords
    no_passwords = params.dig(:mentor, :password).blank? && params.dig(:mentor, :password_confirmation).blank?
    return unless no_passwords

    params[:mentor].delete(:password)
    params[:mentor].delete(:password_confirmation)
  end

  def mentor_verification
    mentor_signed_in? && (current_mentor == find_by_uuid)
  end

  def conditional_action
    if mentor_verification
      yield
    else
      redirect_to_index
    end
  end

  def redirect_to_index(options = {})
    redirect_to mentors_path, options
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def privacy_policy; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper

  # def resource_name
  #   :mentor
  # end
  #
  # def resource
  #   @resource ||= Mentor.new
  # end
  #
  # def devise_mapping
  #   @devise_mapping ||= Devise.mappings[:mentor]
  # end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Nija Developer's Mentor Network</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="mb-5 py-2">
        <ul class="nav justify-content-end">
            <% if mentor_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_mentor_session_path, method: :delete, class: 'nav-link', onclick: 'reloadPage()' %>
              </li>
            <li class="nav-item">
              <%= link_to 'Your Profile', mentor_path(current_mentor.uuid), class: 'nav-link' %>
            </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Become a Mentor', new_mentor_registration_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign In', new_mentor_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          <li class="nav-item">
            <%= link_to 'Find a Mentor', mentors_path, class: 'nav-link' %>
          </li>
  <!--        <li class="nav-item">-->
  <!--          <a class="nav-link" href="#">Donate</a>-->
  <!--        </li>-->
        </ul>
      </nav>
      <div class="container body">
        <%= yield %>
      </div>

<!--      <div class="alert alert-primary col-md-6 offset-md-6">-->
<!--        <p>By using Lola's Lab services you agree to our <%#= link_to "privacy policy", privacy_policy_path, class: "alert-link" %> We operate globally and use cookies to manage log in sessions.-->
<!--        </p>-->
<!--        <span class="alert-link">Close</span>-->
<!--      </div>-->

      <footer class="w-100">
        <hr class="border-white mb-2 mt-5 ml-0">
        <%= link_to 'Privacy Policy', privacy_policy_path, class: 'px-3' %>
      </footer>

      <script>
        function reloadPage() {
            location.reload();
        }

        // function closeCookieNotice() {
        //     remove()
        // }
      </script>
  </body>
</html>

app/views/mentors/edit.html.erb
<div class="col-md-6 offset-md-3">
  <h2 class="display-3 pb-2 title">Edit your profile, <%= @mentor.username %></h2>
  <%= form_for(@mentor, as: resource_name, url: mentor_path(@mentor.uuid), html: { method: :put }) do |f| %>
      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
        <p>Please confirm your email to be listed in the directory: <%= resource.unconfirmed_email %></p>
      <% end %>
      <%= render "mentors/shared/error_messages", resource: resource %>
      <div class="form-group">
        <%= f.label :username %><br />
        <%= f.text_field :username, autocomplete: "username", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :job_role %><br />
        <%= f.text_field :job_role, autocomplete: "job_role", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |c| %>
            <div class="form-checks form-check-inline">
              <div class="form-check-input">
                <%= c.check_box(class: "check_box") %>
              </div>
              <div class="form-check-label px-1">
                <%= c.label(class: "check_box")  %>
              </div>
            </div>
        <% end %>
      </div>

      <div class="form-group">
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
      <% if @minimum_password_length %>
        <br />
        <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
    </div>

      <div class="form-group">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control' %>
    </div>

      <div class="actions">
      <%= f.submit "Update", class: 'btn btn-warning' %>
    </div>
  <% end %>

  <hr class="border-white my-4 ml-0">
  <h3 class="title mb-3">Delete my account</h3>

  <%= button_to "Delete my profile", registration_path(resource_name), class: 'btn btn-danger', data: { confirm: "Are you sure?" }, method: :delete %>
</div>

app/views/mentors/index.html.erb
<h1 class="display-2 pb-2 title">
  Find your mentor
</h1>
<div class="row mt-5">
  <div class="col-md-2 col-sm-6">
    <%= form_tag(results_mentors_path, method: 'get') do %>
      <div class="form-group row">
        <p class="form-title col-form-label pt-0">Filter by speciality</p>
        <div class="col-md-10">
          <%= collection_check_boxes :tags, :ids, Tag.all, :id, :name do |c| %>
            <div class="form-checks form-check-inline">
              <div class="form-check-input">
                <%= c.check_box(class: "check_box") %>
              </div>
              <div class="form-check-label px-1">
                <%= c.label(class: "check_box")  %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="form-group row">
          <div class="col-sm-10">
            <%= submit_tag("Filter", class: "btn btn-primary") %>
          </div>
        </div>
      </div>
    <% end %>
  </div>


  <div class="col-md-8 offset-md-2">
    <div class="row">
      <% @mentors.each do |mentor| %>
        <div class="col-sm-6 col-md-4">
          <div class="card text-white bg-dark border-dark mb-3">
            <div class="card-body">
              <h5 class="card-title"><%= mentor.username %></h5>
              <h6 class="card-subtitle mb-2 text-white-50"><%= mentor.job_role %></h6>
              <% mentor.tags[0..2].each do |tag| %>
                <span class="card-text"><%= tag.name %></span>
              <% end %>
              <%= link_to 'Book a session', mentor.booking_url, class: "mt-1 card-link d-block" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/mentors/new.html.erb
<div class="col-md-6 offset-md-3">
  <h2 class="display-3 pb-2 title">Become a Mentor</h2>
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <%= render "mentors/shared/error_messages", resource: resource %>

    <div class="form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autocomplete: "email", class: 'form-control', required: true %>
      <small id="emailHelp" class="form-text text-50">We'll never share your email with anyone else.</small>
    </div>

    <div class="form-group">
      <%= f.label :username %><br />
      <%= f.text_field :username, autofocus: true, autocomplete: "username", class: 'form-control', required: true  %>
    </div>

    <div class="form-group">
      <%= f.label :job_role %><br />
      <%= f.text_field :job_role, autocomplete: "job_role", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :booking_url %><br />
      <%= f.text_field :booking_url, autofocus: true, autocomplete: "booking_url", class: 'form-control', required: true  %>
      <small id="emailHelp" class="form-text text-50">This should be a link to the service you use to manage bookings e.g. Calendly or Google Forms.</small>

    </div>


    <div class="form-group">
      <%= f.label :password %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password", class: 'form-control', required: true, minlength: 6  %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control', required: true, minlength: 6  %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up", class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= render "mentors/shared/links" %>
</div>

app/views/mentors/results.html.erb
<h1 class="display-2 pb-2 title">
  Find your mentor
</h1>
<div class="row mt-5">
  <div class="col-md-2 col-sm-6">
    <%= form_tag(results_mentors_path, method: 'get') do %>
      <div class="form-group row">
        <p class="form-title col-form-label pt-0">Filter by speciality</p>
        <div class="col-md-10">
          <%= collection_check_boxes :tags, :ids, Tag.all, :id, :name do |c| %>
            <div class="form-checks form-check-inline">
              <div class="form-check-input">
                <%= c.check_box(class: "check_box") %>
              </div>
              <div class="form-check-label px-1">
                <%= c.label(class: "check_box")  %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="form-group row">
          <div class="col-sm-10">
            <%= submit_tag("Filter", class: "btn btn-primary") %>
          </div>
        </div>
      </div>
    <% end %>
  </div>


  <div class="col-md-8 offset-md-2">
    <div class="row">
      <% @mentors.each do |mentor| %>
        <div class="col-sm-6 col-md-4">
          <div class="card text-white bg-dark border-dark mb-3">
            <div class="card-body">
              <h5 class="card-title"><%= mentor.username %></h5>
              <h6 class="card-subtitle mb-2 text-white-50"><%= mentor.job_role %></h6>
              <% mentor.tags.each do |tag| %>
                <span class="card-text"><%= tag.name %></span>
              <% end %>
              <%= link_to 'Book a session', mentor.booking_url, class: "card-link d-block mt-1" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/mentors/root.html.erb
<header class="row">
  <h1 class="display-1 pb-2 title">The Nija Developer's Mentor Network</h1>
  <hr class="border-white my-4 ml-0 w-25" role="presentation">
</header>

<div class="row">
  <section class="lead col-md-8">
    <p>In October 2020, the Nigerians all over the world held protests to push for the disbanding of the Special Anti-Robbery Squad (SARS) and a stop to police brutality in Nigeria. Things escalated and on 20th of October, the military was sent into various parts of the country, security cameras were removed and protesters were murdered. Citizens in Lekki, Lagos, were able to stream the massacre live on social media, branding the event the Lekki Tollgate Massacre.</p>
    <p>Nigerians everywhere were in mourning, and many in the country expressed a passion to obtain skills that could enable them to make the kinds of positive impact on Nigeria. <a href="https://twitter.com/namzo/status/1319385543856316417?s=20">Ernest Ojeh</a> offered to mentor Nigerian developers and international community followed suit.</p>
    <p>This network will not fix Nigeria's systematic problems but it is one of the many ways that will allow Nigerians to do for themselves what Nigeria can not do for them. If you're a developer and have capacity, consider signing up as a mentor and help those back home.</p>
  </section>

</div>

<div class="row mb-5">
  <section class="call-to-actions col-md-6 offset-md-3">
    <%= link_to 'Become a Mentor', new_mentor_registration_path, class: 'btn btn-primary btn-lg a-btn mx-4' %>
    <%= link_to 'Find a Mentor', mentors_path, class: 'btn btn-primary btn-lg a-btn' %>
  </section>
</div>

app/views/mentors/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/mentors/shared/_links.html.erb
<div class="mt-4">
  <%- if !current_page?(new_mentor_session_path) %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.registerable? && !current_page?(new_mentor_registration_path) %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.recoverable? && !current_page?(new_mentor_registration_path) %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <%#- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <%# end %>

  <%#- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%#= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <%# end %>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>

</div>

app/views/mentors/show.html.erb
<h1><%= @mentor.username %></h1>

<% if !@mentor.confirmed? %>
  <p>Please confirm your email: <%= link_to 'Confirm my account', confirmation_url(@mentor, :confirmation_token => @mentor.confirmation_token) %></p>
<% end %>

<h5><%= @mentor.job_role %></h5>
<% @mentor.tags.each do |tag| %>
  <p><%= tag.name %></p>
<% end %>
<% if current_mentor == @mentor %>
  <%= link_to "Edit", edit_mentor_path(@mentor.uuid) %>
<% else %>
  <%= link_to "Book a time", @mentor.booking_url %>
<% end %>